linters:
    flake8:
    eslint:
        config: './eslint.config'
    csslint:
        ignore: 'box-model,ids,padding,height,width,webkit-appearance,moz-appearance,*,box-sizing,input,outline:none'

files:
    ignore: